[build]
target = "avr-unknown-gnu-atmega328"
rustflags = ["--emit=llvm-ir"]

# [target.avr-unknown-gnu-atmega328]

[unstable]
build-std = ["core", "alloc"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
