[build]
target = "avr-unknown-gnu-atmega328"
# rustflags = ["--emit=llvm-ir"]

[unstable]
build-std = ["core", "alloc"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[alias]
build-rom = "run --package xtask --"
