[package]
name = "xtask-build-rom"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
colored = "2.1.0"
tree-sitter = "0.23.0"
tree-sitter-c = "0.23.0"

[build-dependencies]
cc="*"
